Week 9 Assignment To Do App
pesto-students/p5-ankit-jimishgajjar pull request #9
Opened 2022-11-10 09:05 UTC by jimishgajjar

Week 9 To Do Application Assignment Using React Class Component, States & Props.

2022-11-12 16:37 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      todos: [].concat(updatedItems),
this.setState({todos: updatedItems});

2022-11-12 16:38 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      todos: [].concat(updatedItems),
same as above

2022-11-12 16:39 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +        editId: "",
add this.setState({
  labelVal: "",
  discriptionVal: "",
  editId: "",
 todos: this.state.todos
})

2022-11-12 16:39 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      return todo;
why you are returning this?

2022-11-12 16:39 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +  TaskUndo = (itemId) => {
change function name

2022-11-12 16:40 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      todos: [].concat(undoItems),
same as above mentioned comments

2022-11-12 16:41 UTC, subhadip-pesto requested changes

2022-11-12 16:41 UTC, subhadip-pesto commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      todos: [].concat(updatedItems),
Fixx all given comments

2022-11-12 19:58 UTC, jimishgajjar commented on Week-9/to-do-app/src/components/containers/TodoContainer.js
> +      todos: [].concat(updatedItems),
Changes Updated

2022-11-13 17:22 UTC, subhadip-pesto approved these changes

2022-11-14 16:04 UTC, merged